### ISSUE TITLE
incompatible with epic loot ? on load up

### ISSUE THREAD

**Issue by SDUBZ** [blaxxun-boop/Vitality#3]
[Error  :   BepInEx] Could not load [Cooking 1.1.11] because it is incompatible with: randyknapp.mods.extendeditemdataframework
[Error  :   BepInEx] Could not load [Dual Wield 1.0.5] because it is incompatible with: randyknapp.mods.epicloot
[Error  :   BepInEx] Could not load [Vitality 1.1.0] because it is incompatible with: randyknapp.mods.epicloot
seems like these versions are affected
would love to have them work with epic loot if not to hard to do

**Comment by blaxxun-boop** [comment]
As a general rule of thumbs: If you see something like that, the other mod is the issue. It has bugs I cannot fix, because they are not my mods.
E.g. Extended Item Data Framework messes with stats of cooked food, basically randomizing them.
Epic Loot multiplies the damage of your enchantments on your weapon by 4, if you dual wield.
Epic Loot multiplies the health gained by Vitality over and over again, eventually you will end up with thousands of HP.

Server owners complain about this to me, for some reason, because people on their server abuse this to cheat, and eventually I get sick of it and add the incompatibility flag.

Yes, all of this can be fixed easily, but not by me, but by the author of the other mods.

**Comment by SDUBZ** [comment]
> As a general rule of thumbs: If you see something like that, the other mod is the issue. It has bugs I cannot fix, because they are not my mods. E.g. Extended Item Data Framework messes with stats of cooked food, basically randomizing them. Epic Loot multiplies the damage of your enchantments on your weapon by 4, if you dual wield. Epic Loot multiplies the health gained by Vitality over and over again, eventually you will end up with thousands of HP.
> 
> Server owners complain about this to me, for some reason, because people on their server abuse this to cheat, and eventually I get sick of it and add the incompatibility flag.
> 
> Yes, all of this can be fixed easily, but not by me, but by the author of the other mods.

sorry for the inconveniencece im just new to modding valheim
i will make a issue with the other dev
